apiVersion: apps/v1
kind: Deploymnent
metadata:
  name: my-deploymnent
  labels:
    env: dev
spec:
  # number of desired pods 
  replicas: 3
  # selector for the pods that this ReplicaSet manages
  selector:
    matchLabels:
      env: dev
  # template for the pods that the ReplicaSet creates      
  template:
    metadata:
      name: mypod
      labels:
        env: dev
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
          - containerPort: 80  
 