apiVersion: v1
kind: Namespace
metadata:
  name: dev

# kubectl create -f namespace.yaml
# kubectl get ns
# kubectl describe ns research
# kubectl get pods --namespace=research
# kubectl run --image=redis redis --namespace=finance  
# To see pods on all the name spaces at a time
 # kubectl get pods --all-namespaces
 # kubectl get pods -A
 