apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec: 
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 500mi
  

# Kubectl create -f pvc-definition.yaml
# kubectl get persistentvolumeclaim

Reclaim policy    Description
Retain             Keeps PV and it's data 
Delete             Deletes PV