apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod

# Using config in a manifest files  
apiVersion: v1
kind: Pod 
metadata:
  name: simple-webapp-color 
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080
    envFrom:
      - ConfigMapRef:
          name: app-config

# to pass multiple env variables use the below 
    envFrom:
      - ConfigMapRef:
          name: app-config

# To pass sigle env variable use the below.
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR

# To pass the env variable as a volume
volumes:
- name: app-config-volume
  configMap:
    name: app-config

