apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  conatiners:
  - name: web-app
    image: web-app
    ports:
     - containerPort: 8080
  initConatiners:   
  - name: db-checker
    image: busybox
    command: 'wait-for-db-to-start.sh'