apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  conatiners:
  - name: web-app
    image: web-app
    ports:
     - containerPort: 8080
  initConatiners:   
  - name: log-shipper
    image: busybox
    command: 'setup-log-shipper.sh'
    restartPolicy: Always